### ISSUE TITLE
Regex of TokenType have to be \w{8} not \d{8}

### ISSUE THREAD

**Issue by KIM-KOOKHYUN** [line/line-blockchain-developers-sdk-js#39]
### Default information
* lbd-sdk-js version: `e.g. 1.2.0`

### Description of the bug
request.ts > TokenType class > tokeTypeFormat parameters
#### Example codes
When token type is 0000002a on updateFungibleTokenMediaResources api, this api is not working.

#### Error logs
Error: Invalid tokenType: invalid format of tokenId, valid format is /\d{8}/
    at Function.from (node_modules/@line/lbd-sdk-js/dist/request.js:192:19)
    at /Users/user/git/developers-sdk-js-qa-client/node_modules/@line/lbd-sdk-js/dist/request.js:197:64
    at arrayMap (node_modules/lodash/lodash.js:653:23)
    at Function.map (node_modules/lodash/lodash.js:9622:14)
    at Function.fromMulti (node_modules/@line/lbd-sdk-js/dist/request.js:197:33)
    at HttpClient.updateFungibleTokenMediaResources (node_modules/@line/lbd-sdk-js/dist/http-client-base.js:407:48)
    at Context.<anonymous> (file:///Users/user/git/developers-sdk-js-qa-client/src/test/item-token-controller/fungible/UpdateFungibleTokensIcon.js:11:41)
    at processImmediate (node:internal/timers:464:21)

### Anything else we need to know
You have to modify tokenTypeFormat from **\\d{8}** to **\\w{8} or [\\da-z]{8}**

**Comment by ryukato** [comment]
PTAL #40
